### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Gerlot** [y8hamon/Slide-To-Unlock#1]
Hi!

Can I ask what license do you provide yout library with? Is it ok to use it in a commercial project?

**Comment by y8hamon** [comment]
Hello,

The project is under Creative Commons licensing:
http://creativecommons.org/licenses/by-sa/4.0/
Thanks for using my code.

Best regards.

2015-04-01 15:58 GMT+02:00 Gerlot <notifications@github.com>:

> Hi!
>
> Can I ask what license do you provide yout library with? Is it ok to use
> it in a commercial project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/y8hamon/Slide-To-Unlock/issues/1>.
>



-- 
Yoann HAMON

**Comment by Gerlot** [comment]
Thank you very much for your quick response!
